### ISSUE TITLE
Widen CLA Scope

### ISSUE THREAD

**Issue by briantopping** [clahub/clahub#61] opened 2014-05-04 17:43 UTC
Hi all, cool project, thanks for keeping it going!

I need to have a CLA for the scope of a whole organization, not just individual repos.  When new repos are added, they should be covered by the existing CLA, not require a new CLA to be signed.  

IANAL, but the way things are articulated, it would be easy for a layperson to be convinced that the CLAs here reflect against individual repos, and a new repo that was created without it being included in CLAHub could be confused for a CLA not being required for that repo.

**Comment by mitar** [comment] 2016-08-08 08:15
Duplicate of #82?

**Comment by briantopping** [comment] 2016-08-08 13:54
Aren't duplicates considered in chronological order?

**Comment by mitar** [comment] 2016-08-08 17:15
Not always. The other issue have more information and more participation. But I marked both as duplicates and I am leaving to maintainers to decide.

**Comment by ryanttb** [comment] 2016-12-13 20:44
@mitar Agreed. Closing this one as duplicate as there is more activity on #82

**Closed by ryanttb** 2016-12-13 20:44 UTC

**Comment by briantopping** [comment] 2016-12-13 20:50
Yah good luck with it all. I filed this, what, 2.5 years ago? I doubt it will go very far. And that activity... A bunch of thumbs up. Woo hoo.

Whatever.
